- hosts: master
  become: yes
  vars:
      username: salim

  tasks:
    - name: Creates directory
      file:
        path: /home/{{ username }}/docker
        state: directory

    - name: Download containerd deb
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.6.6-1_amd64.deb
        dest: /home/{{ username }}/docker/containerd.io_1.6.6-1_amd64.deb

    - name: Download docker cli deb
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb
        dest: /home/{{ username }}/docker/docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb

    - name: Download docker ce deb
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb
        dest: /home/{{ username }}/docker/docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb

    - name: Download Docker rootless deb
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-rootless-extras_20.10.9~3-0~ubuntu-focal_amd64.deb
        dest: /home/{{ username }}/docker/docker-ce-rootless-extras_20.10.9~3-0~ubuntu-focal_amd64.deb

    - name: Download Docker comose plugin deb
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-compose-plugin_2.6.0~ubuntu-focal_amd64.deb
        dest: /home/{{ username }}/docker/docker-compose-plugin_2.6.0~ubuntu-focal_amd64.deb

    - name: Download Docker scan deb
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-scan-plugin_0.9.0~ubuntu-focal_amd64.deb
        dest: /home/{{ username }}/docker/docker-scan-plugin_0.9.0~ubuntu-focal_amd64.deb

    - name: Download Docker cri-d deb
      get_url:
        url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.1/cri-dockerd-0.2.1.amd64.tgz
        dest: /home/{{ username }}/docker/cri-dockerd-0.2.1.amd64.tgz

    - name: Download cri-d service file
      get_url:
        url: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
        dest: /home/{{ username }}/docker/cri-docker.service

    - name: Download cri-d socket file
      get_url:
        url: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
        dest: /home/{{ username }}/docker/cri-docker.socket
